"""add email verification user relationship

Revision ID: d186002a095d
Revises: 937a1e57af16
Create Date: 2025-08-20 15:56:41.471981+09:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd186002a095d'
down_revision: Union[str, None] = '937a1e57af16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 기존 테이블들은 건드리지 않고, email_verifications에만 user_id 컬럼 추가
    op.add_column('email_verifications', sa.Column('user_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_email_verifications_user_id'), 'email_verifications', ['user_id'], unique=False)
    op.create_foreign_key(None, 'email_verifications', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # email_verifications에서 user_id 컬럼만 제거
    op.drop_constraint(None, 'email_verifications', type_='foreignkey')
    op.drop_index(op.f('ix_email_verifications_user_id'), table_name='email_verifications')
    op.drop_column('email_verifications', 'user_id')
    # ### end Alembic commands ###