"""change_diaries_keywords_to_json_type

Revision ID: 18f4dc743b40
Revises: 67b6bc23eedc
Create Date: 2025-08-21 21:27:01.131888+09:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "18f4dc743b40"
down_revision: Union[str, None] = "67b6bc23eedc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 수동으로 USING 절을 포함한 ALTER COLUMN 실행
    op.execute(
        "ALTER TABLE diaries ALTER COLUMN keywords TYPE JSON USING keywords::json"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 롤백시 JSON에서 VARCHAR로 변환
    op.execute(
        "ALTER TABLE diaries ALTER COLUMN keywords TYPE VARCHAR USING keywords::text"
    )
    # ### end Alembic commands ###
