"""fix_email_verifications_field_name_is_verified_to_is_used

Revision ID: 84b70cfbe731
Revises: 4b122182651e
Create Date: 2025-08-22 10:15:15.920186+09:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84b70cfbe731'
down_revision: Union[str, None] = '4b122182651e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 1. 기본값과 함께 새 컬럼 추가
    op.add_column('email_verifications', sa.Column('is_used', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    
    # 2. 기존 데이터를 새 컬럼으로 복사
    op.execute("UPDATE email_verifications SET is_used = is_verified WHERE is_verified IS NOT NULL")
    
    # 3. 기존 컬럼 삭제
    op.drop_column('email_verifications', 'is_verified')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 1. 기존 컬럼 다시 추가
    op.add_column('email_verifications', sa.Column('is_verified', sa.BOOLEAN(), autoincrement=False, nullable=False, server_default=sa.text('false')))
    
    # 2. 데이터를 기존 컬럼으로 복구
    op.execute("UPDATE email_verifications SET is_verified = is_used WHERE is_used IS NOT NULL")
    
    # 3. 새 컬럼 삭제
    op.drop_column('email_verifications', 'is_used')
    # ### end Alembic commands ###