"""add_notifications_table_and_update_notification_settings

Revision ID: 4b122182651e
Revises: 18f4dc743b40
Create Date: 2025-08-22 10:09:44.749832+09:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b122182651e'
down_revision: Union[str, None] = '18f4dc743b40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 1. notifications 테이블 생성
    op.create_table('notifications',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('user_id', sa.UUID(), nullable=False),
        sa.Column('type', sa.String(length=50), nullable=False),
        sa.Column('title', sa.String(length=255), nullable=False),
        sa.Column('message', sa.Text(), nullable=False),
        sa.Column('data', sa.JSON(), nullable=True),
        sa.Column('is_read', sa.Boolean(), nullable=False),
        sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.CheckConstraint("type IN ('diary_reminder','report_ready','ai_complete')", name='ck_notification_type'),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_notification_type', 'notifications', ['type', 'scheduled_at'])
    op.create_index('idx_unread_notifications', 'notifications', ['user_id', 'is_read', 'created_at'], 
                    postgresql_where=sa.text('is_read = false'))
    op.create_index('idx_user_notifications', 'notifications', ['user_id', 'created_at'])
    
    # 2. notification_settings 테이블 필드 업데이트
    # 기본값과 함께 새 컬럼 추가
    op.add_column('notification_settings', sa.Column('push_enabled', sa.Boolean(), nullable=False, server_default=sa.text('true')))
    op.add_column('notification_settings', sa.Column('diary_reminder_enabled', sa.Boolean(), nullable=False, server_default=sa.text('true')))
    op.add_column('notification_settings', sa.Column('diary_reminder_time', sa.String(length=5), nullable=True, server_default=sa.text("'21:00'")))
    op.add_column('notification_settings', sa.Column('diary_reminder_days', sa.JSON(), nullable=True, server_default=sa.text("'[]'")))
    op.add_column('notification_settings', sa.Column('report_notification_enabled', sa.Boolean(), nullable=False, server_default=sa.text('true')))
    op.add_column('notification_settings', sa.Column('ai_processing_enabled', sa.Boolean(), nullable=False, server_default=sa.text('true')))
    op.add_column('notification_settings', sa.Column('browser_push_enabled', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    
    # 기존 데이터 마이그레이션 (기존 enabled 값을 push_enabled로 복사)
    op.execute("UPDATE notification_settings SET push_enabled = enabled WHERE enabled IS NOT NULL")
    op.execute("UPDATE notification_settings SET diary_reminder_enabled = diary_reminder WHERE diary_reminder IS NOT NULL")
    op.execute("UPDATE notification_settings SET ai_processing_enabled = ai_content_ready WHERE ai_content_ready IS NOT NULL")
    
    # 기존 컬럼 삭제
    op.drop_column('notification_settings', 'friend_share')
    op.drop_column('notification_settings', 'anniversary')
    op.drop_column('notification_settings', 'frequency')
    op.drop_column('notification_settings', 'enabled')
    op.drop_column('notification_settings', 'quiet_hours_enabled')
    op.drop_column('notification_settings', 'emotion_trend')
    op.drop_column('notification_settings', 'quiet_start_time')
    op.drop_column('notification_settings', 'quiet_end_time')
    op.drop_column('notification_settings', 'diary_reminder')
    op.drop_column('notification_settings', 'ai_content_ready')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 1. 기존 컬럼들 다시 추가 (데이터 백업용)
    op.add_column('notification_settings', sa.Column('ai_content_ready', sa.BOOLEAN(), autoincrement=False, nullable=False, server_default=sa.text('true')))
    op.add_column('notification_settings', sa.Column('diary_reminder', sa.BOOLEAN(), autoincrement=False, nullable=False, server_default=sa.text('true')))
    op.add_column('notification_settings', sa.Column('quiet_end_time', sa.VARCHAR(length=5), autoincrement=False, nullable=True, server_default=sa.text("'08:00'")))
    op.add_column('notification_settings', sa.Column('quiet_start_time', sa.VARCHAR(length=5), autoincrement=False, nullable=True, server_default=sa.text("'22:00'")))
    op.add_column('notification_settings', sa.Column('emotion_trend', sa.BOOLEAN(), autoincrement=False, nullable=False, server_default=sa.text('true')))
    op.add_column('notification_settings', sa.Column('quiet_hours_enabled', sa.BOOLEAN(), autoincrement=False, nullable=False, server_default=sa.text('false')))
    op.add_column('notification_settings', sa.Column('enabled', sa.BOOLEAN(), autoincrement=False, nullable=False, server_default=sa.text('true')))
    op.add_column('notification_settings', sa.Column('frequency', sa.VARCHAR(length=20), autoincrement=False, nullable=False, server_default=sa.text("'immediate'")))
    op.add_column('notification_settings', sa.Column('anniversary', sa.BOOLEAN(), autoincrement=False, nullable=False, server_default=sa.text('true')))
    op.add_column('notification_settings', sa.Column('friend_share', sa.BOOLEAN(), autoincrement=False, nullable=False, server_default=sa.text('false')))
    
    # 2. 데이터 복구 (신규 컬럼에서 기존 컬럼으로 데이터 복사)
    op.execute("UPDATE notification_settings SET enabled = push_enabled WHERE push_enabled IS NOT NULL")
    op.execute("UPDATE notification_settings SET diary_reminder = diary_reminder_enabled WHERE diary_reminder_enabled IS NOT NULL")
    op.execute("UPDATE notification_settings SET ai_content_ready = ai_processing_enabled WHERE ai_processing_enabled IS NOT NULL")
    
    # 3. 신규 컬럼들 삭제
    op.drop_column('notification_settings', 'browser_push_enabled')
    op.drop_column('notification_settings', 'ai_processing_enabled')
    op.drop_column('notification_settings', 'report_notification_enabled')
    op.drop_column('notification_settings', 'diary_reminder_days')
    op.drop_column('notification_settings', 'diary_reminder_time')
    op.drop_column('notification_settings', 'diary_reminder_enabled')
    op.drop_column('notification_settings', 'push_enabled')
    
    # 4. notifications 테이블 삭제
    op.drop_index('idx_user_notifications', table_name='notifications')
    op.drop_index('idx_unread_notifications', table_name='notifications')
    op.drop_index('idx_notification_type', table_name='notifications')
    op.drop_table('notifications')
    # ### end Alembic commands ###