"""migrate to sqlalchemy 2.0

Revision ID: 062a7cce5af1
Revises: d186002a095d
Create Date: 2025-08-20 16:12:19.618190+09:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '062a7cce5af1'
down_revision: Union[str, None] = 'd186002a095d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 기존 테이블들은 건드리지 않고, SQLAlchemy 2.0 호환성을 위한 최소한의 변경만 수행
    # 실제로는 모델 정의만 변경되었으므로 데이터베이스 구조 변경은 없음
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 기존 테이블들은 건드리지 않음
    pass
    # ### end Alembic commands ###