"""change email verification to is_used

Revision ID: change_email_verification_to_is_used
Revises: 1e2f7f09025c
Create Date: 2025-08-22 00:00:00.000000+09:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'change_email_to_is_used'
down_revision: Union[str, None] = '1e2f7f09025c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 현재 DB 상태가 이미 원하는 상태이므로 아무것도 하지 않음
    # is_used 컬럼과 verified_at 컬럼이 이미 존재함
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # email_verifications 테이블만 롤백 (다른 테이블은 건드리지 않음)
    op.add_column('email_verifications', sa.Column('is_verified', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('email_verifications', sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_column('email_verifications', 'used_at')
    op.drop_column('email_verifications', 'is_used')
    # ### end Alembic commands ###
