"""add_diary_date_field

Revision ID: 1a2b3c4d5e6f
Revises: 25d195aa2d5b
Create Date: 2025-01-27 12:00:00.000000+09:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "1a2b3c4d5e6f"
down_revision: Union[str, None] = "25d195aa2d5b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Check if column already exists before adding
    connection = op.get_bind()
    inspector = sa.inspect(connection)
    columns = [col['name'] for col in inspector.get_columns('diaries')]
    
    if 'diary_date' not in columns:
        op.add_column('diaries', sa.Column('diary_date', sa.Date(), nullable=True))
    
    # Check if index already exists before creating
    indexes = [idx['name'] for idx in inspector.get_indexes('diaries')]
    if 'ix_diaries_diary_date' not in indexes:
        op.create_index(op.f('ix_diaries_diary_date'), 'diaries', ['diary_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_diaries_diary_date'), table_name='diaries')
    op.drop_column('diaries', 'diary_date')
    # ### end Alembic commands ###
