"""add_verification_type_to_email_verification

Revision ID: 1e2f7f09025c
Revises: 062a7cce5af1
Create Date: 2025-08-21 13:37:47.165823+09:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1e2f7f09025c'
down_revision: Union[str, None] = '062a7cce5af1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 이메일 인증 관련만 수정 (다른 사람 작업 영역은 건드리지 않음)
    op.add_column('email_verifications', sa.Column('verification_type', sa.String(length=10), nullable=False, server_default='signup'))
    op.add_column('email_verifications', sa.Column('is_verified', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('email_verifications', sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_column('email_verifications', 'is_used')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 이메일 인증 관련만 롤백 (다른 사람 작업 영역은 건드리지 않음)
    op.add_column('email_verifications', sa.Column('is_used', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('email_verifications', 'verified_at')
    op.drop_column('email_verifications', 'is_verified')
    op.drop_column('email_verifications', 'verification_type')
    # ### end Alembic commands ###